import 'package:nbgospel/model/user_model.dart';

const List<UserModel> originalList = [
  UserModel(
    pic: 'assets/nbgospel_youtube_channel1.jpg',
    firstName: 'Follow Our',
    lastName: 'Youtube Channel',
    fullName: 'Follow Our Youtube Channel',
    url: 'https://www.youtube.com/channel/UCxx6Da5GMdNJ1Okuv_F0FXg',
  ),
  UserModel(
    pic: 'assets/Whatsapp.jpg',
    firstName: 'Join Our',
    lastName: 'WhatsApp Group',
    fullName: 'Join our whatsapp group',
    url: 'https://nbgospel.com/whatapp-group-links/',
  ),
  UserModel(
    pic: 'assets/Twitter.jpg',
    firstName: 'Follow Our',
    lastName: 'Twitter page',
    fullName: 'Follow our twitter page',
    url: 'https://twitter.com/GospelNb?t=WDnl44XpDLBjr5iX2CGivw&s=09',
  ),
  UserModel(
    pic: 'assets/telegram.jpg',
    firstName: 'Join Our',
    lastName: 'Telegram Channel',
    fullName: 'Join our telegram channel',
    url: 'https://nbgospel.com/whatapp-group-links/',
  ),
  UserModel(
    pic: 'assets/facebook.jpg',
    firstName: 'Follow Our',
    lastName: 'Facebook page',
    fullName: 'Follow our facebook page',
    url: 'https://www.facebook.com/Nbgospel/ ',
  ),
  UserModel(
    pic: 'assets/Apostle Arome Osayi.jpg',
    firstName: 'Apostle Arome',
    lastName: 'Osayi',
    fullName: 'Apostle Arome Osayi',
    url: 'https://nbgospel.com/download-apostle-arome-osayi-messages-2021/',
  ),
  UserModel(
    pic: 'assets/Apostle Edu Udechukwu.jpg',
    firstName: 'Apostle Edu',
    lastName: 'Udechukwu',
    fullName: 'Apostle Edu Udechukwu',
    url: 'https://nbgospel.com/download-all-apostle-edu-udechukwu-messages/',
  ),
  UserModel(
    pic: 'assets/Bishop David Abioye.jpg',
    firstName: 'Bishop David',
    lastName: 'Abioye',
    fullName: 'Bishop David Abioye',
    url: 'https://nbgospel.com/download-bishop-david-abioye-messages/',
  ),
  UserModel(
    pic: 'assets/Apostle Johnson Suleman 1.jpg',
    firstName: 'Apostle Johnson',
    lastName: 'Suleman',
    fullName: 'Apostle Johnson Suleman',
    url: 'https://nbgospel.com/apostle-johnson-suleman-messages-2021-mp3/',
  ),
  UserModel(
    pic: 'assets/Apostle Joshua Selman.jpg',
    firstName: 'Apostle Joshua',
    lastName: 'Selman',
    fullName: 'Apostle Joshua Selman',
    url: 'https://nbgospel.com/download-apostle-joshua-selman-messages/',
  ),
  UserModel(
    pic: 'assets/Apostle Michael Orokpo.jpg',
    firstName: 'Apostle Michael',
    lastName: 'Orokpo',
    fullName: 'Apostle Michael Orokpo',
    url: 'https://nbgospel.com/download-apostle-michael-orokpo-messages-mp3/',
  ),
  UserModel(
    pic: 'assets/Bro Gbile Akanni.jpg',
    firstName: 'Bro Gbile',
    lastName: 'Akanni',
    fullName: 'Bro Gbile Akanni',
    url: 'https://nbgospel.com/download-bro-gbile-akanni-messages/',
  ),
  UserModel(
    pic: 'assets/Dr John Akpami.jpg',
    firstName: 'Rev John',
    lastName: 'Akpami',
    fullName: 'Rev John Akpami',
    url: 'https://nbgospel.com/reverend-john-akpami-messages/',
  ),
  UserModel(
    pic: 'assets/Healing.jpg',
    firstName: 'Messages on',
    lastName: 'Healing',
    fullName: 'Messages on Healing',
    url: 'https://nbgospel.com/messages-on-healing-and-deliverance/',
  ),
  UserModel(
    pic: 'assets/Joel Osteen.jpg',
    firstName: 'Pastor Joel',
    lastName: 'Osteen',
    fullName: 'Joel Osteen',
    url: 'https://nbgospel.com/free-audio-download-joel-osteen-sermons/',
  ),
  UserModel(
    pic: 'assets/P. Daneil.jpg',
    firstName: 'Pastor Daniel',
    lastName: 'Olawande',
    fullName: 'Pastor Daniel Olawande',
    url: 'https://nbgospel.com/pastor-daniel-olawande-messages/',
  ),
  UserModel(
    pic: 'assets/Pastor Chingtok Ishaku.jpg',
    firstName: 'Pastor Chingtok',
    lastName: 'Ishaku',
    fullName: 'Pastor Chingtok Ishaku',
    url: 'https://nbgospel.com/pastor-chingtok-ishaku-messages-mp3/',
  ),
  UserModel(
    pic: 'assets/quotes.png',
    firstName: 'Inspirational',
    lastName: 'Quotes',
    fullName: 'Inspirational Quotes',
    url: 'https://nbgospel.com/short-inspirational-gospel-quotes-for-the-day/',
  ),
  UserModel(
    pic: 'assets/Pastor Chris Devin.jpg',
    firstName: 'Pastor Chris',
    lastName: 'Delvan',
    fullName: 'Pastor Chris Delvan',
    url: 'https://nbgospel.com/chris-delvan-gwamna-messages-and-songs/',
  ),
  UserModel(
    pic: 'assets/Pastor Chris Oyakhilome 2.jpg',
    firstName: 'Pastor Chris',
    lastName: 'Oyakhilome',
    fullName: 'Pastor Chris Oyakhilome',
    url: 'https://nbgospel.com/download-pastor-chris-oyakhilome-messages/',
  ),
  UserModel(
    pic: 'assets/Pastor David Ogbueli.jpg',
    firstName: 'Pastor David',
    lastName: 'Ogbueli',
    fullName: 'Pastor David Ogbueli',
    url: 'https://nbgospel.com/download-pastor-david-ogbueli-messages/',
  ),
  UserModel(
    pic: 'assets/Prophet Isah El Buba2.jpg',
    firstName: 'Prophet Isah',
    lastName: 'El Buba',
    fullName: 'Prophet Isah El Buba',
    url: 'https://nbgospel.com/prophet-isah-el-buba-messages/',
  ),
  UserModel(
    pic: 'assets/Pastor E.A Adeboye.jpg',
    firstName: 'Pastor E.A',
    lastName: 'Adeboye',
    fullName: 'Pastor E.A Adeboye',
    url: 'https://nbgospel.com/pastor-ea-adeboye-messages/',
  ),
  UserModel(
    pic: 'assets/Bishop David Oyedepo.jpg',
    firstName: 'Bishop David',
    lastName: 'Oyedepo',
    fullName: 'Bishop David oyedepo',
    url: 'https://nbgospel.com/bishop-david-oyedepo-messages/',
  ),
  UserModel(
    pic: 'assets/Pastor Mildred Okonkwo.jpg',
    firstName: 'Pastor Mildred',
    lastName: 'Okonkwo',
    fullName: 'Pastor Mildred Okonkwo',
    url: 'https://nbgospel.com/pastor-mildred-okonkwo-messages-on-marriage/',
  ),
  UserModel(
    pic: 'assets/Marriage.jpg',
    firstName: 'Messages on',
    lastName: 'Marriage',
    fullName: 'Messages on marriage',
    url:
        'https://nbgospel.com/download-audio-messages-on-marriage-and-e-books/',
  ),
  UserModel(
    pic: 'assets/Pastor Derick Prince.jpg',
    firstName: 'Pastor Derick',
    lastName: 'Prince',
    fullName: 'Pastor Derick Prince',
    url:
        'https://nbgospel.com/download-derek-prince-sermons-audio-and-book-collections/',
  ),
  UserModel(
    pic: 'assets/Pastor Femi Lazarus.jpg',
    firstName: 'Pastor Femi',
    lastName: 'Lazarus',
    fullName: 'Pastor Femi Lazarus',
    url: 'https://nbgospel.com/download-pastor-femi-lazarus-messages/',
  ),
  UserModel(
    pic: 'assets/Pastor Paul Enenche 2.jpg',
    firstName: 'Pastor Paul',
    lastName: 'Enenche',
    fullName: 'Pastor Paul Enenche',
    url: 'https://nbgospel.com/audio-of-dr-pastor-paul-enenche-messages-mp3/',
  ),
  UserModel(
    pic: 'assets/Pastor W.F. Kumuyi.jpg',
    firstName: 'Pastor W.F.',
    lastName: 'Kumuyi',
    fullName: 'Pastor W.F. Kumuyi',
    url:
        'https://nbgospel.com/dlcm-download-pastor-wf-kumuyi-messages-2021-mp3/',
  ),
  UserModel(
    pic: 'assets/Prayer.jpg',
    firstName: 'Messages on',
    lastName: 'Prayer',
    fullName: 'Messages on Prayer',
    url:
        'https://nbgospel.com/download-audio-messages-on-prayer-and-spiritual-gifts/',
  ),
  UserModel(
    pic: 'assets/Prophet Jesse Janfa.jpg',
    firstName: 'Prophet Jesse',
    lastName: 'Janfa',
    fullName: 'Prophet Jesse Janfa',
    url: 'https://nbgospel.com/download-all-prophet-jesse-janfa-messages/',
  ),
  UserModel(
    pic: 'assets/Reverend Gideon Odoma.jpg',
    firstName: 'Reverend Gideon',
    lastName: 'Odoma',
    fullName: 'Reverend Gideon Odoma',
    url:
        'https://nbgospel.com/recent-mp3-download-all-rev-gideon-odoma-messages-here/',
  ),
  UserModel(
    pic: 'assets/Reverend Tolu Agboola.jpg',
    firstName: 'Reverend Tolu',
    lastName: 'Agboola',
    fullName: 'Reverend Tolu Agboola',
    url: 'https://nbgospel.com/download-all-reverend-tolu-agboola-messages/',
  ),
  UserModel(
    pic: 'assets/Pastor Paul Adefarasin.jpg',
    firstName: 'Pastor Paul',
    lastName: 'Adefarasin',
    fullName: 'Pastor Paul Adefarasin',
    url:
        'https://nbgospel.com/download-derek-prince-sermons-audio-and-book-collections/',
  ),
  UserModel(
    pic: 'assets/T.D. Jakes.jpg',
    firstName: 'Bishop T.D.',
    lastName: 'Jakes',
    fullName: 'Bishop T.D. Jakes',
    url: 'https://nbgospel.com/download-t-d-jakes-sermons-and-books/',
  ),
  UserModel(
    pic: 'assets/ngb1.jpg',
    firstName: 'Written Sermons',
    lastName: '',
    fullName: 'Written Sermons',
    url:
        'https://nbgospel.com/short-free-sermons-and-sermon-outlines-for-pastors/',
  ),
  UserModel(
    pic: 'assets/Pastor Jerry Eze.jpg',
    firstName: 'Pastor Jerry',
    lastName: 'Eze',
    fullName: 'Pastor Jerry Eze',
    url: 'https://nbgospel.com/pastor-jerry-eze-sermons/',
  ),
  UserModel(
    pic: 'assets/Pastor Poju Oyemadu.jpg',
    firstName: 'Pastor Poju',
    lastName: 'Oyemadu',
    fullName: 'Pastor Poju Oyemadu',
    url: 'https://nbgospel.com/pastor-poju-oyemadu-messages/',
  ),
  UserModel(
    pic: 'assets/error.jpg',
    firstName: 'REPORT AN',
    lastName: 'ERROR',
    fullName: 'Report an Error',
    url:
        'https://docs.google.com/forms/d/e/1FAIpQLScP9Z7PXHypye0Qdo1rY48JUo3VRMJ-tRExKM-cbGor1cCGNg/viewform?usp=sf_link',
  ),
];
